### ISSUE TITLE
Sample from a SBM

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/xdata-igraph#2]
Just do an ER for each pair of blocks.

**Comment by jovo** [comment]
indeed, it is relatively easy to write a double loop over clusters, including dealing with different sized groups.
it would be even easier if one could specify the parameters and igraph would do it.
in particular, there are a few ways of specifying SBM 'parameters', eg, 

1) pi, B: B is KxK matrix of elements in (0,1) and pi is a K-dimensional probability vector
2) nvec, B: nvec K-dimensional integer valued vector specifying the # of vertices per cluster

and, of course, one must specify whether it is directed and/or contains self-loops.
if self-loops are forbidden, the diagonal blocks must be handled differently than the off-diagonal,
and in either case, if things are undirected, the diagonal and off-diagonal must be treated differently.

anyway, you are clearly correct that none of this is difficult, although i think all of it would be useful.

**Comment by gaborcsardi** [comment]
Yes, this issue is about having the algorithm implemented in igraph. :) "Just do an ER..." is for myself, not for you. :)

**Comment by jovo** [comment]
ah, cool, got it.  yes, just do an ER :)

On Tue, Oct 22, 2013 at 9:58 AM, Gabor Csardi notifications@github.comwrote:

> Yes, this issue is about having the algorithm implemented in igraph. :)
> "Just do an ER..." is for myself, not for you. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaborcsardi/igraph/issues/2#issuecomment-26804780
> .

## 

perhaps consider allowing the quest for eudaimonia to guide you
openconnecto.me, jovo.me

**Comment by jovo** [comment]
so it's done?! in master, or some other branch? i'd love to play....

**Comment by jovo** [comment]
oh, i see now, it is in the development branch, right?
