### ISSUE TITLE
yeppp! new math kernel useful?

### ISSUE THREAD

**Issue by jovo** [igraph/xdata-igraph#23]
http://www.yeppp.info/

it seems to have a good license ("licensed under the New (3-clause) BSD license, an OSI-approved permissive license."), and have good performance on certain benchmarks, and has a pure C interface.  i'm not qualified to assess, but maybe @gaborcsardi or @dmhembe1 is?

**Comment by gaborcsardi** [comment]
How would you use this? Instead of Rmath? Pretty much impossible.

Also, it is more or less experimental, regardless of what it says about itself: https://bitbucket.org/MDukhan/yeppp/issues?status=new&status=open has things like '# 2: Add pow function', '# 12: Add rounding functions (floor, ceil, trunc, round)', etc. So it does not have any of these.....

**Comment by jovo** [comment]
i guess i was just misremembering this earlier email exchange:

"better/faster/generaler embedding methodologies, potentially swapping out ARPACK with, eg, intel MKL, to facilitate parallel, distributed, and GPU computations.

We cannot use MKL in igraph, its license is not compatible. I mean, we can use it in our projects, but this software cannot be distributed, even in binary form. We can use it for analysis or in a web service, but that's all. However, MKL points to FEAST (http://www.ecs.umass.edu/~polizzi/feast/features.htm), which is open source, but it only implements symmetric eigensolvers. These are working very well in ARPACK as well, only the non-symmetri ones are problematic, so I would not switch right now. "

in retrospect, yeppp does not seem relevant for that.  nonetheless, i am reminded of this discussion, and various options.  perhaps i shall open a new issue for someone to investigate options such as those listed here: http://www.grycap.upv.es/slepc/ or here: http://www.grycap.upv.es/slepc/documentation/reports/str6.pdf
?

**Comment by gaborcsardi** [comment]
Yepp is not useful (at this point), so we can close this here. There is already an ARPACK issue here:  https://github.com/igraph/igraph/issues/551
