### ISSUE TITLE
python igraph?

### ISSUE THREAD

**Issue by jovo** [igraph/xdata-igraph#24]
is there a plan to continue developing igraph in python, or only R for now?

**Comment by gaborcsardi** [comment]
In xdata, there are no plans for Python AFAIK. Which means that there are no promises that I'll add Python interface to xdata stuff.

In general, the Python interface of igraph is fully supported.

**Comment by jovo** [comment]
so, just for clarity, functions like: adjacency-spectral embedding, triangle counting, and scan stat, 
you do not expect to support in python?

**Comment by gaborcsardi** [comment]
Eventually they will, I think. But I do not consider this a blocking issue. In other words, to consider my part of xdata as "done", python interface is not required, imo.

Btw. it would also help if you could contribute by writing the docs for the R version of these functions. I think you can do this better than me, as you are the most familiar with these methods.

**Comment by jovo** [comment]
> Eventually they will, I think. But I do not consider this a blocking
> issue. In other words, to consider my part of xdata as "done", python
> interface is not required, imo.
> 
> ok, i understand.
> 
> Btw. it would also help if you could contribute by writing the docs for
> the R version of these functions. I think you can do this better than me,
> as you are the most familiar with these methods.
> 
> yes, for sure! can you make an issue for each function that needs to be
> better documented, and assign me, and i'll get them done.  also, if your
> docs follow a particular protocol, perhaps point me to a good example as
> well?

thanks, j

> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/igraph/xdata-igraph/issues/24#issuecomment-33481039
> .

## 

perhaps consider allowing the quest for eudaimonia to guide you
openconnecto.me, jovo.me

**Comment by gaborcsardi** [comment]
> yes, for sure! can you make an issue for each function that needs to be
> better documented, and assign me, and i'll get them done.  also, if your
> docs follow a particular protocol, perhaps point me to a good example as
> well?

You already created some issues, how about finishing those. Btw. by "you" I mean somebody from your group, obviously. :) 

As for examples, there is plenty in the package already. But it is just plain R documentation, as it is explained in "Writing R extensions". I'll copy over the docs to the C manual (and Python when applicable) once they are written.

**Comment by jovo** [comment]
> You already created some issues, how about finishing those. Btw. by "you"
> I mean somebody from your group, obviously. :)
> 
> i had hoped so :-)
> 
> As for examples, there is plenty in the package already. But it is just
> plain R documentation, as it is explained in "Writing R extensions". I'll
> copy over the docs to the C manual (and Python when applicable) once they
> are written.

ok....

> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/igraph/xdata-igraph/issues/24#issuecomment-33482110
> .

## 

perhaps consider allowing the quest for eudaimonia to guide you
openconnecto.me, jovo.me
