### ISSUE TITLE
ASE on the Laplacian

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/xdata-igraph#41]
Daniel:

> I would like to be able to embed the graph laplacian either normalized or non-normalized. Possible options include D-A, I-D^{-1/2}AD^{-1/2}, D^{-1/2}AD^{-1/2}. There are other versions such as the regularized version [Karl Rohe](http://www.stat.wisc.edu/~karlrohe/homepage/Welcome_files/RSC_arxiv.pdf) came up with.

From #38.

**Comment by gaborcsardi** [comment]
Maybe this should be called `laplacian.spectral.embedding` or `lse` then?

**Comment by dpmcsuss** [comment]
Yes, `lse` is fine, with options to indicate which of the various versions we want.

**Comment by gaborcsardi** [comment]
What is the definition you want for the Laplacian of a directed graph? Most definitions do not make much sense, maybe this is the best: F. Chung, Laplacians and the Cheeger inequality for directed graphs, Annals of Combinatorics 9 (2005), pp. 1-19

**Comment by gaborcsardi** [comment]
Actually docs are missing.... and the directed case, too.

**Comment by dpmcsuss** [comment]
Sorry for ignoring this earlier. Again it might be good to have a couple options. The version in Chung is symmetric which seems strange for a directed graph.

I think http://arxiv.org/pdf/1204.2296v1.pdf Eq (2.3) would be my preference for the default.
