### ISSUE TITLE
ASE: use eigendecomposition for undirected graphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/xdata-igraph#44]
From #42.

**Comment by gaborcsardi** [comment]
This actually brings up some issues, e.g. we cannot scale using the square root of the eigenvalues any more, as they are not guaranteed to be non-negative. Should the user get an error message if `scaled=TRUE` and the graph is undirected?

**Comment by dpmcsuss** [comment]
Usually we take the square root of absolute values. Additionally, this should not come up very often in the largest algebraic setup.

For Largest Magnitude, It might be useful to return the eigenvalues in the output list since then people can check their signs if necessary.
