### ISSUE TITLE
glust.rsvt and getAICc

### ISSUE THREAD

**Issue by sd2803** [igraph/xdata-igraph#55]
They are referred to in the book (Csardi, Nepusz and Airoldi) but, don't seem to be in the R package. Would appreciate any link to it, or some sort of description of what they do.
Thanks. Sid
sd2803@columbia.edu

**Comment by szhorvat** [comment]
Unfortunately I don't know the answer to this. At the time when this question was asked, this repo was already inactive and unmonitored.

Please ask future igraph questions at https://igraph.discourse.group/
