### ISSUE TITLE
correlated ER sampling

### ISSUE THREAD

**Issue by jovo** [igraph/xdata-igraph#8]
input: either 1 graph and a correlation value, rho, between 0 & 1, or p and a correlation value.

output: 2 graphs sampled with the specified n,p and rho

**Comment by gaborcsardi** [comment]
I guess this is related to GSM #1. Or they are the same? Or this is a subset of #1? Probably.

**Comment by jovo** [comment]
indeed they are related.
the function called 'CER<-function( n, p, rho ,permutation)'
in there is the function to generate correlated ER graphs.
i guess if you specify one of the graphs, then they need not be correlated _ER_ graphs technically.
the reason this comes up in SGM is because we have theory that SGM works when the data are correlated ER graphs, so we wanted to show numerically that it works.
but really, i think of these as two different things:

1) a method for sampling a pair of graphs
2) a method of matching a pair of graphs

obviously, both related.
