### ISSUE TITLE
find the elbow in the scree plot

### ISSUE THREAD

**Issue by jovo** [igraph/xdata-igraph#9]
for many latent position models, a model selection procedure is necessary to choose the dimension into which we embed.  we like the approach from this:
http://sas.uwaterloo.ca/~aghodsib/papers/ADS.pdf

**Comment by gaborcsardi** [comment]
> hi josh, do you have sample code for this? unless it has been implemented by you, and we can benchmark our 
> implementation against yours, this item should go in the second phase -- optimize -- rather than in the first phase -- 
> replicate. pls advise. edo
> 
> ## 
> 
> Edoardo M. Airoldi

**Comment by gaborcsardi** [comment]
> i don't know what Joshua has in mind,
> but this seems like an R thing ... why would it be an igraph thing?
> 
> ---carey

**Comment by jovo** [comment]
believe youngser might have R code for this.
it seems that this package has implemented it in R already:
http://cran.r-project.org/web/packages/rrcovHD/rrcovHD.pdf
in particular, OutlierPCDist says that it chooses the dimension via the profile likelihood method of Zhu and Ghodsi

so, i'm not sure whether you guys think this is worth implementing in igraph or not.
it is something that we tend to use often for choosing the dimension into which to embed.  
i have neither a strong opinion or preference with regard to where the code lives to implement this, this comment was just one of the several requests made in carey's office that day, which i was reporting here for prosperity, as requested.

**Comment by gaborcsardi** [comment]
The Zhu-Ghodsi method is kind of trivial, with some tricks it is possible to make it linear I think, even if numerically a bit less stable.

**Comment by gaborcsardi** [comment]
Need the benchmarking framework (#6) before committing the improved version.....

**Comment by jovo** [comment]
indeed, i recall writing matlab code for it myself one day.
let's see what youngser says...

On Sun, Nov 24, 2013 at 10:42 PM, Gabor Csardi notifications@github.comwrote:

> The Zhu-Ghodsi method is kind of trivial, with some tricks it is possible
> to make it linear I think, even if numerically a bit less stable.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gaborcsardi/igraph/issues/9#issuecomment-29175859
> .

## 

perhaps consider allowing the quest for eudaimonia to guide you
openconnecto.me, jovo.me
